<?php

namespace AdminPanel\Server;

use AdminPanel\Entry;

/*
 * Server is a class in which the logs are coming from.
 * @param string $name        The name of the server. i.e. 'http', 'ssh', 'log', 'monitor'
 * @param integer $curConns   The number of connections on the server.
 * @param array $activity     An array of logs generated by the server.
 */

class Server
{
    protected $name;
    protected $curConns = 0;
    protected $activity = [];

    public function __construct($name)
    {
		$this->setName($name);
	}

    public function getName()
	{
        return $this->name;
    }

    public function getCurConns()
	{
        return $this->curConns;
    }

    public function getActivity()
	{
        $output = '';
        foreach($this->activity as $entry) $output .= $entry->__toString();
        return $output;
    }

    public function setName($name)
	{
        $this->name = $name;
    }

    public function setCurConns($curConns)
	{
        $this->user = $curConns;
    }

    public function setActivity(array $activity)
	{
        $this->activity = $activity;
    }

    public function addActivity(Entry $entry)	
	{
        try{
			$this->activity[] = $entry;
		}catch(Exception $e){
			echo 'Caught exception, Entry not a log format: ', $e->getMessage()."\n";
		}

    }

	abstract function getLog();
    
}
